--Credits to Tyler Blevins on V3rmillion
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Fhume97")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Hello! I'm Fhume, what can I get for you today? (Menu is above)")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Give them 3 warnings then contact a MR/HR for help.")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Use the hand-to GUI(Press H on PC).")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Yes.")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Having bacon hair.")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Manager")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Located on the Trello in our communications server.")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "No.")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Attend shifts, trainings or reach a certain amount of points.")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Yes, you should join it code is 2nfuc3Z")
wait(0.9)
game.ReplicatedStorage.RemoteFunction:InvokeServer("SendData", "Yes, check the game store!")
wait(0.5)