-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
-- Remote Path: game:GetService("Workspace").artem606.Combat.combatClientScript.replicator
 
local A_1 = "punch"
local Event = game:GetService("Workspace").artem606.Combat.combatClientScript.replicator
Event:FireServer(A_1)
